import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

const RemoteTitle = dynamic(
  () => {
    return import("home/ab5c7957-76ed-4403-8fc0-ddb62a8dfd24");
  },
  { ssr: false }
);

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>Yo yo bitch</p>
          <RemoteTitle />
        </div>
      </main>
    </>
  );
}
